- name: download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp

- name: unarchive prometheus
  unarchive:
    remote_src: true
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp

- name: create prometheus group
  group:
    name: prometheus

- name: create prometheus users
  user:
    name: prometheus

- name: create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Install binaries to /usr/local/bin
  copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    remote_src: true
    owner: root
    group: root
    mode: 0755
  with_items:
    - prometheus
    - promtool

- name: Install prometheus files to /etc/prometheus
  copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
    dest: /etc/prometheus
    remote_src: true
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - consoles
    - console_libraries

- name: install prometheus config file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  tags:
    - config_file

- name: install unit file to systemd
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644

- name: configure systemd to use service
  systemd:
    daemon_reload: true
    enabled: true
    state: restarted
    name: prometheus.service
