- hosts: all
  roles:
    - crypto

- hosts: work_servers
  vars:
    node_exporter_version: 1.3.1
  roles:
    - install-docker
    - install-node-exporter

- hosts: management_servers
  vars:
    node_exporter_version: 1.3.1
    prometheus_version: 2.21.0
  pre_tasks:
    - setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['work_servers'] }}"
  roles:
    - install-node-exporter
    - install-prometheus
